language: android

android:
  components:
    - platform-tools
    - android-22
    - build-tools-22.0.1
    - extra

jdk:
  - openjdk7
   
notifications:
  email: false

# Turn off caching to avoid any caching problems
# cache: false

# Use the Travis Container-Based Infrastructure
sudo: false

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
script: ./gradlew clean build
