project_identifier: KitchenTimer
api_key: KeepTheAPIkeySecret
base_url: https://api.crowdin.com
base_path: /path/to/your/project
preserve_hierarchy: true

files:
  -
   source: '/app/src/*/res/values/strings.xml'
   translation: '/%original_path%-%android_code%/%original_file_name%'
   languages_mapping:
      android_code:
         af: af
         am: am
         ar: ar
         ast: es-rXA
         az: az
         be: be
         bg: bg
         bn: bn
         ca: ca
         cs: cs
         da: da
         de: de
         el: el
         es-ES: es
         et: et
         eu: eu
         fa: fa
         fi: fi
         fr: fr
         gl: gl
         he: iw
         hi: hi
         hr: hr
         hu: hu
         hy-AM: hy
         id: in
         is: is
         it: it
         ja: ja
         ka: ka
         km: km
         ko: ko
         ku: ku
         lb: lb
         lo: lo
         lt: lt
         lv: lv
         ml-IN: ml
         mn: mn
         ms: ms
         nb: nb
         ne-NP: ne
         nl: nl
         pa-IN: pa
         pl: pl
         pt-PT: pt
         rm-CH: rm
         ro: ro
         ru: ru
         si-LK: si
         sk: sk
         sl: sl
         sr: sr
         sv-SE: sv
         sw: sw
         ta: ta
         th: th
         tl: tl
         tr: tr
         ug: ug
         uk: uk
         vi: vi
         zu: zu
